// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for OrderStatus.
const (
	INVALID    OrderStatus = "INVALID"
	NEW        OrderStatus = "NEW"
	PROCESSED  OrderStatus = "PROCESSED"
	PROCESSING OrderStatus = "PROCESSING"
)

// Order defines model for Order.
type Order struct {
	Accrual    *float32    `json:"accrual,omitempty"`
	Number     string      `json:"number"`
	Status     OrderStatus `json:"status"`
	UploadedAt time.Time   `json:"uploaded_at"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// WithdrawalRequest defines model for WithdrawalRequest.
type WithdrawalRequest struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// WithdrawalResponse defines model for WithdrawalResponse.
type WithdrawalResponse struct {
	Order       string  `json:"order"`
	ProcessedAt string  `json:"processed_at"`
	Sum         float32 `json:"sum"`
}

// PostAPIUserOrdersTextBody defines parameters for PostAPIUserOrders.
type PostAPIUserOrdersTextBody = string

// PostAPIUserBalanceWithdrawJSONRequestBody defines body for PostAPIUserBalanceWithdraw for application/json ContentType.
type PostAPIUserBalanceWithdrawJSONRequestBody = WithdrawalRequest

// PostAPIUserLoginJSONRequestBody defines body for PostAPIUserLogin for application/json ContentType.
type PostAPIUserLoginJSONRequestBody = UserCredentials

// PostAPIUserOrdersTextRequestBody defines body for PostAPIUserOrders for text/plain ContentType.
type PostAPIUserOrdersTextRequestBody = PostAPIUserOrdersTextBody

// PostAPIUserRegisterJSONRequestBody defines body for PostAPIUserRegister for application/json ContentType.
type PostAPIUserRegisterJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// create a new withdrawal for user
	// (POST /api/user/balance/withdraw)
	PostAPIUserBalanceWithdraw(w http.ResponseWriter, r *http.Request)
	// login user
	// (POST /api/user/login)
	PostAPIUserLogin(w http.ResponseWriter, r *http.Request)
	// get user orders
	// (GET /api/user/orders)
	GetAPIUserOrders(w http.ResponseWriter, r *http.Request)
	// upload users order
	// (POST /api/user/orders)
	PostAPIUserOrders(w http.ResponseWriter, r *http.Request)
	// register user
	// (POST /api/user/register)
	PostAPIUserRegister(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств
	// (GET /api/user/withdrawals)
	GetAPIUserWithdrawals(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// create a new withdrawal for user
// (POST /api/user/balance/withdraw)
func (_ Unimplemented) PostAPIUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// login user
// (POST /api/user/login)
func (_ Unimplemented) PostAPIUserLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get user orders
// (GET /api/user/orders)
func (_ Unimplemented) GetAPIUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// upload users order
// (POST /api/user/orders)
func (_ Unimplemented) PostAPIUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// register user
// (POST /api/user/register)
func (_ Unimplemented) PostAPIUserRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение информации о выводе средств
// (GET /api/user/withdrawals)
func (_ Unimplemented) GetAPIUserWithdrawals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAPIUserBalanceWithdraw operation middleware
func (siw *ServerInterfaceWrapper) PostAPIUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAPIUserBalanceWithdraw(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAPIUserLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAPIUserLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAPIUserLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAPIUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetAPIUserOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAPIUserOrders operation middleware
func (siw *ServerInterfaceWrapper) PostAPIUserOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAPIUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAPIUserRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAPIUserRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAPIUserRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAPIUserWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) GetAPIUserWithdrawals(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIUserWithdrawals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/balance/withdraw", wrapper.PostAPIUserBalanceWithdraw)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.PostAPIUserLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/orders", wrapper.GetAPIUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/orders", wrapper.PostAPIUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.PostAPIUserRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/withdrawals", wrapper.GetAPIUserWithdrawals)
	})

	return r
}

type PostAPIUserBalanceWithdrawRequestObject struct {
	Body *PostAPIUserBalanceWithdrawJSONRequestBody
}

type PostAPIUserBalanceWithdrawResponseObject interface {
	VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error
}

type PostAPIUserBalanceWithdraw200Response struct {
}

func (response PostAPIUserBalanceWithdraw200Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostAPIUserBalanceWithdraw400Response struct {
}

func (response PostAPIUserBalanceWithdraw400Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostAPIUserBalanceWithdraw401Response struct {
}

func (response PostAPIUserBalanceWithdraw401Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostAPIUserBalanceWithdraw402Response struct {
}

func (response PostAPIUserBalanceWithdraw402Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(402)
	return nil
}

type PostAPIUserBalanceWithdraw422Response struct {
}

func (response PostAPIUserBalanceWithdraw422Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type PostAPIUserBalanceWithdraw500Response struct {
}

func (response PostAPIUserBalanceWithdraw500Response) VisitPostAPIUserBalanceWithdrawResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostAPIUserLoginRequestObject struct {
	Body *PostAPIUserLoginJSONRequestBody
}

type PostAPIUserLoginResponseObject interface {
	VisitPostAPIUserLoginResponse(w http.ResponseWriter) error
}

type PostAPIUserLogin200ResponseHeaders struct {
	Authorization string
}

type PostAPIUserLogin200Response struct {
	Headers PostAPIUserLogin200ResponseHeaders
}

func (response PostAPIUserLogin200Response) VisitPostAPIUserLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Authorization", fmt.Sprint(response.Headers.Authorization))
	w.WriteHeader(200)
	return nil
}

type PostAPIUserLogin400Response struct {
}

func (response PostAPIUserLogin400Response) VisitPostAPIUserLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostAPIUserLogin401Response struct {
}

func (response PostAPIUserLogin401Response) VisitPostAPIUserLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostAPIUserLogin500Response struct {
}

func (response PostAPIUserLogin500Response) VisitPostAPIUserLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetAPIUserOrdersRequestObject struct {
}

type GetAPIUserOrdersResponseObject interface {
	VisitGetAPIUserOrdersResponse(w http.ResponseWriter) error
}

type GetAPIUserOrders200JSONResponse []Order

func (response GetAPIUserOrders200JSONResponse) VisitGetAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAPIUserOrders204Response struct {
}

func (response GetAPIUserOrders204Response) VisitGetAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetAPIUserOrders401Response struct {
}

func (response GetAPIUserOrders401Response) VisitGetAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetAPIUserOrders500Response struct {
}

func (response GetAPIUserOrders500Response) VisitGetAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostAPIUserOrdersRequestObject struct {
	Body *PostAPIUserOrdersTextRequestBody
}

type PostAPIUserOrdersResponseObject interface {
	VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error
}

type PostAPIUserOrders200Response struct {
}

func (response PostAPIUserOrders200Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostAPIUserOrders202Response struct {
}

func (response PostAPIUserOrders202Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type PostAPIUserOrders400Response struct {
}

func (response PostAPIUserOrders400Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostAPIUserOrders401Response struct {
}

func (response PostAPIUserOrders401Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostAPIUserOrders409Response struct {
}

func (response PostAPIUserOrders409Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type PostAPIUserOrders422Response struct {
}

func (response PostAPIUserOrders422Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type PostAPIUserOrders500Response struct {
}

func (response PostAPIUserOrders500Response) VisitPostAPIUserOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostAPIUserRegisterRequestObject struct {
	Body *PostAPIUserRegisterJSONRequestBody
}

type PostAPIUserRegisterResponseObject interface {
	VisitPostAPIUserRegisterResponse(w http.ResponseWriter) error
}

type PostAPIUserRegister200ResponseHeaders struct {
	Authorization string
}

type PostAPIUserRegister200Response struct {
	Headers PostAPIUserRegister200ResponseHeaders
}

func (response PostAPIUserRegister200Response) VisitPostAPIUserRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Authorization", fmt.Sprint(response.Headers.Authorization))
	w.WriteHeader(200)
	return nil
}

type PostAPIUserRegister400Response struct {
}

func (response PostAPIUserRegister400Response) VisitPostAPIUserRegisterResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostAPIUserRegister409Response struct {
}

func (response PostAPIUserRegister409Response) VisitPostAPIUserRegisterResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type PostAPIUserRegister500Response struct {
}

func (response PostAPIUserRegister500Response) VisitPostAPIUserRegisterResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetAPIUserWithdrawalsRequestObject struct {
}

type GetAPIUserWithdrawalsResponseObject interface {
	VisitGetAPIUserWithdrawalsResponse(w http.ResponseWriter) error
}

type GetAPIUserWithdrawals200JSONResponse []WithdrawalResponse

func (response GetAPIUserWithdrawals200JSONResponse) VisitGetAPIUserWithdrawalsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAPIUserWithdrawals204Response struct {
}

func (response GetAPIUserWithdrawals204Response) VisitGetAPIUserWithdrawalsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type GetAPIUserWithdrawals401Response struct {
}

func (response GetAPIUserWithdrawals401Response) VisitGetAPIUserWithdrawalsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetAPIUserWithdrawals500Response struct {
}

func (response GetAPIUserWithdrawals500Response) VisitGetAPIUserWithdrawalsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// create a new withdrawal for user
	// (POST /api/user/balance/withdraw)
	PostAPIUserBalanceWithdraw(ctx context.Context, request PostAPIUserBalanceWithdrawRequestObject) (PostAPIUserBalanceWithdrawResponseObject, error)
	// login user
	// (POST /api/user/login)
	PostAPIUserLogin(ctx context.Context, request PostAPIUserLoginRequestObject) (PostAPIUserLoginResponseObject, error)
	// get user orders
	// (GET /api/user/orders)
	GetAPIUserOrders(ctx context.Context, request GetAPIUserOrdersRequestObject) (GetAPIUserOrdersResponseObject, error)
	// upload users order
	// (POST /api/user/orders)
	PostAPIUserOrders(ctx context.Context, request PostAPIUserOrdersRequestObject) (PostAPIUserOrdersResponseObject, error)
	// register user
	// (POST /api/user/register)
	PostAPIUserRegister(ctx context.Context, request PostAPIUserRegisterRequestObject) (PostAPIUserRegisterResponseObject, error)
	// Получение информации о выводе средств
	// (GET /api/user/withdrawals)
	GetAPIUserWithdrawals(ctx context.Context, request GetAPIUserWithdrawalsRequestObject) (GetAPIUserWithdrawalsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAPIUserBalanceWithdraw operation middleware
func (sh *strictHandler) PostAPIUserBalanceWithdraw(w http.ResponseWriter, r *http.Request) {
	var request PostAPIUserBalanceWithdrawRequestObject

	var body PostAPIUserBalanceWithdrawJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAPIUserBalanceWithdraw(ctx, request.(PostAPIUserBalanceWithdrawRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAPIUserBalanceWithdraw")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAPIUserBalanceWithdrawResponseObject); ok {
		if err := validResponse.VisitPostAPIUserBalanceWithdrawResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAPIUserLogin operation middleware
func (sh *strictHandler) PostAPIUserLogin(w http.ResponseWriter, r *http.Request) {
	var request PostAPIUserLoginRequestObject

	var body PostAPIUserLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAPIUserLogin(ctx, request.(PostAPIUserLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAPIUserLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAPIUserLoginResponseObject); ok {
		if err := validResponse.VisitPostAPIUserLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAPIUserOrders operation middleware
func (sh *strictHandler) GetAPIUserOrders(w http.ResponseWriter, r *http.Request) {
	var request GetAPIUserOrdersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIUserOrders(ctx, request.(GetAPIUserOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIUserOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAPIUserOrdersResponseObject); ok {
		if err := validResponse.VisitGetAPIUserOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAPIUserOrders operation middleware
func (sh *strictHandler) PostAPIUserOrders(w http.ResponseWriter, r *http.Request) {
	var request PostAPIUserOrdersRequestObject

	data, err := io.ReadAll(r.Body)
	if err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't read body: %w", err))
		return
	}
	body := PostAPIUserOrdersTextRequestBody(data)
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAPIUserOrders(ctx, request.(PostAPIUserOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAPIUserOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAPIUserOrdersResponseObject); ok {
		if err := validResponse.VisitPostAPIUserOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAPIUserRegister operation middleware
func (sh *strictHandler) PostAPIUserRegister(w http.ResponseWriter, r *http.Request) {
	var request PostAPIUserRegisterRequestObject

	var body PostAPIUserRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAPIUserRegister(ctx, request.(PostAPIUserRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAPIUserRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAPIUserRegisterResponseObject); ok {
		if err := validResponse.VisitPostAPIUserRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAPIUserWithdrawals operation middleware
func (sh *strictHandler) GetAPIUserWithdrawals(w http.ResponseWriter, r *http.Request) {
	var request GetAPIUserWithdrawalsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIUserWithdrawals(ctx, request.(GetAPIUserWithdrawalsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIUserWithdrawals")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAPIUserWithdrawalsResponseObject); ok {
		if err := validResponse.VisitGetAPIUserWithdrawalsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
