// Code generated by MockGen. DO NOT EDIT.
// Source: internal/withdrawals/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/iliaonishchenko/gophermart/internal/models"
)

// MockWithdrawalsRepository is a mock of WithdrawalsRepository interface.
type MockWithdrawalsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalsRepositoryMockRecorder
}

// MockWithdrawalsRepositoryMockRecorder is the mock recorder for MockWithdrawalsRepository.
type MockWithdrawalsRepositoryMockRecorder struct {
	mock *MockWithdrawalsRepository
}

// NewMockWithdrawalsRepository creates a new mock instance.
func NewMockWithdrawalsRepository(ctrl *gomock.Controller) *MockWithdrawalsRepository {
	mock := &MockWithdrawalsRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawalsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalsRepository) EXPECT() *MockWithdrawalsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWithdrawalsRepository) Create(ctx context.Context, withdrawalToCreate *models.Withdrawal) (*models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, withdrawalToCreate)
	ret0, _ := ret[0].(*models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWithdrawalsRepositoryMockRecorder) Create(ctx, withdrawalToCreate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWithdrawalsRepository)(nil).Create), ctx, withdrawalToCreate)
}

// Get mocks base method.
func (m *MockWithdrawalsRepository) Get(ctx context.Context) ([]*models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]*models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWithdrawalsRepositoryMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWithdrawalsRepository)(nil).Get), ctx)
}
